title: Somebody4545
iconURL: https://avatars.githubusercontent.com/u/79165198?v=4
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  github: Somebody4545

plugins:
 - jekyll-feed
 - jekyll-seo-tag
